### ISSUE TITLE
JSONRPC notifications support

### ISSUE THREAD

**Issue by rumkin** [bigstepinc/jsonrpc-bidirectional#25]
As I see in code supported JSONRPC version is 2.0. But this version has [notifications](http://www.jsonrpc.org/specification#notification) and according to [source](https://github.com/bigstepinc/jsonrpc-bidirectional/blob/7862cd32d5cf433d300d45183e93a664a11da636/src/Plugins/Client/WebRTCTransport.js#L121) such behavior will cause an error.

**Comment by oxygen** [comment]
Yeah, they were left out as there was no real gain with either asynchronous or synchronous use cases, in other programming languages as well.

Do you have a specific need for fire and forget calls?

**Comment by rumkin** [comment]
I have methods which server calls to notify client. If there is no id your library throws an error.  In other way server will wait for response.

**Comment by oxygen** [comment]
**# Implemented.**

This closes this feature request #27
