### ISSUE TITLE
is it possible to use sockjs instead of websocket?

### ISSUE THREAD

**Issue by gengshenghong** [bigstepinc/jsonrpc-bidirectional#52]
Thank you for this great library.

It seems using 'http' transport, it does not support 'bidirectional rpc call'? In my case, I need to use birectional rpc call using http long polling, if Websocket is support, is it ok to use sockjs instead? As we can control sockjs low-level transport method.

Technically, I guess it works, but, anyone tried this?

Thanks,
Shenghong

**Comment by oxygen** [comment]
Currently there are no transports implemented for JSON-RPC over streams.

Visual Studio Code had a stream based JSON-RPC implemention for the UI to talk to the backend. See their library.

https://github.com/Microsoft/vscode-languageserver-node/tree/master/jsonrpc

You can attempt to write a transport for it (see the transport client plugins for WebSocket and others as an example). It will be a bit difficult with large messages and detecting the end of a JSON to begin parsing (and even more difficult to multiplex severa messages at the same time), something which a WebSocket takes care of automatically.
