### ISSUE TITLE
Bi-directional websocket example seems impossible to port

### ISSUE THREAD

**Issue by aniongithub** [bigstepinc/jsonrpc-bidirectional#59]
My RPC server endpoint has dependencies that cannot be loaded on the client side (client is ES6 browser, server is Node.js) and your example requires me to register a [server endpoint to instantiate bi-directional RPC](https://github.com/bigstepinc/jsonrpc-bidirectional#:~:text=var%20wsJSONRPCRouter%20%3D%20new%20JSONRPC.BidirectionalWebsocketRouter(jsonrpcServer)%3B) calls.

This makes no sense to me since the server side method we're calling is specified as a string [here](https://github.com/bigstepinc/jsonrpc-bidirectional#:~:text=clientOfBidirectionalWS.rpc(%22ping%22%2C%20%5B%22Calling%20from%20html%20es5%20client%2C%20websocket%20transport%20with%20bidirectional%20JSONRPC.%22%5D)).

Is there a bidirectional sample where the ES6 client doesn't have to have access to the server RPC endpoint class? Some simple getting started examples would be much appreciated!

**Comment by oxygen** [comment]
The EndpointBase class is for exporting an interface to receive RPCs on either side of a bidirectional connection which works over WebSocket and other protocols which allow bidirectional request-response. It can also be used for standard HTTP servers.

The `strPath` property represents a HTTP request path where HTTP is involved.

The client needs to specify a HTTP path for the default HTTP client (unidirectional requests) or when handshaking a WebSocket connection. The path then identifies the interface where the RPC is to be routed (the method name in the JSON-RPC 2.0 request needs to be a method defined on the endpoint)

There are fully working examples right on the front page. You can also read the tests, they are essentially a fully working app covering 99% of functionality.

Just put a little more time in reading the examples on the front page of this project and all will be clear.

**Comment by oxygen** [comment]
I don’t have admin rights anymore on this project although I have created it on my dime and I’m the main contributor (over 99% I think).

As such I cannot help you any further and can’t even close this issue.

Have a nice day :)

**Comment by aniongithub** [comment]
@oxygen Thanks for the prompt reply! I'm going to try and put together a complete sample and will link it here after going through the tests and samples again. I'll leave this open for a bit so I can ask you any specific questions about the sample.

**Comment by aniongithub** [comment]
@oxygen was right, I just needed to go over the samples much more carefully and then adapt a couple of things to use express with it, etc. In any case, to share what I learned - I've put up working examples here in this repo.

https://github.com/aniongithub/jsonrpc-bidirectional-examples

Hope it helps someone else!

**Comment by oxygen** [comment]
@aniongithub 

Glad to see you succeed.

This library is in use with tens of project, and with the exception of WebRTC data channel (it worked great for SSH terminals, but at the time we were shorthanded and never launched that specific project), all the transports have seen lots of production use.

I wish I had the time and/or the resources to convert it to TypeScript to benefit from the superior transpiled code which integrates much better with various module loaders and is a much cleaner javascript with no runtime dependencies.

I have forwarded your examples to a friend who coincidentally was actually in need of integrating with express just 1-2 weeks ago for some personal project of his.

Thanks a lot :)
